name: Release

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential clang curl flex git libssl-dev lld llvm python3 python-is-python3 zip zstd

      - name: Build kernel
        run: |
          ./build.sh all
          mv ${{ github.workspace }}/../out ${{ github.workspace }}/out

      - name: Upload kernel
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/out/anykernel/Hana-kernel-renoir-*.zip
            ${{ github.workspace }}/out/magisk/Hana-kernel-renoir-*.img
